/**
 * The FLOWER solution: where the four tubes are, and how to drop a ball into one.
 *
 * Generated by tools/flowertable.ts. A FLOWER cannot be loaded through its retrieval
 * opening -- the intake only touches a ball at the mouth, and a ball in the bin has no path
 * back to it (tools/flowerprobe.ts: four balls in, roller reversed six seconds, four balls
 * still there, at every flower and every stand-off). The way in is over the top, which is
 * PHYSICS_AND_SIMULATION.md 7.2's trough lob.
 *
 * The targets travel in the same file as the solution on purpose: a second file to keep in
 * step is a second file to get out of step.
 */

export interface FlowerCell {
  hoodDeg: number;
  rpm: number;
  /** How far the crossing sits inside the hole, inches. The whole tolerance is 0.6. */
  clearance_in: number;
  descentDeg: number;
  /** Half-width of the speed band that still drops in, as a fraction. */
  margin: number;
}

export interface FlowerRowRaw extends FlowerCell { range_in: number }

export class FlowerTable {
  /** The tubes, FTC inches. */
  readonly flowers: { x: number; y: number }[] = [];
  private readonly rows: FlowerRowRaw[] = [];

  constructor(rows: FlowerRowRaw[], flowers: { x: number; y: number }[]) {
    this.rows = [...rows].sort((a, b) => a.range_in - b.range_in);
    this.flowers = flowers;
  }

  static fromCsv(csv: string): FlowerTable {
    const rows: FlowerRowRaw[] = [];
    const flowers: { x: number; y: number }[] = [];
    for (const line of csv.trim().split(/\r?\n/)) {
      const f = /^#\s*flower\d+=(-?[\d.]+),(-?[\d.]+)/.exec(line);
      if (f) { flowers.push({ x: Number(f[1]), y: Number(f[2]) }); continue; }
      if (line.startsWith('#') || line.startsWith('range_in')) continue;
      const [r, hood, rpm, , clr, desc, m] = line.split(',').map(Number);
      if (Number.isFinite(r)) rows.push({ range_in: r, hoodDeg: hood, rpm, clearance_in: clr, descentDeg: desc, margin: m });
    }
    return new FlowerTable(rows, flowers);
  }

  get isEmpty(): boolean { return this.rows.length === 0; }
  get minRange(): number { return this.rows.length ? this.rows[0].range_in : 0; }
  get maxRange(): number { return this.rows.length ? this.rows[this.rows.length - 1].range_in : 0; }

  /**
   * The shot from this stand-off, or null outside the solved band.
   *
   * Null is a real answer: past 26 in the lob needs a hood steeper than the travel, and
   * inside 8 in the robot's own bumper is against the tube. Interpolating past either end
   * would hand the robot an angle that solves nothing, which is the mistake the CELL table
   * made for a whole day (docs/DECISIONS.md, "the brain fired from inside the table").
   */
  lookup(range_in: number): FlowerCell | null {
    const r = this.rows;
    if (!r.length || range_in < r[0].range_in || range_in > r[r.length - 1].range_in) return null;
    for (let i = 1; i < r.length; i++) {
      if (range_in <= r[i].range_in) {
        const t = (range_in - r[i - 1].range_in) / (r[i].range_in - r[i - 1].range_in || 1);
        const mix = (a: number, b: number) => a + t * (b - a);
        return {
          hoodDeg: mix(r[i - 1].hoodDeg, r[i].hoodDeg),
          rpm: mix(r[i - 1].rpm, r[i].rpm),
          // The narrower of the two, not the blend: halfway between a forgiving stand-off
          // and a marginal one is not a forgiving shot.
          clearance_in: Math.min(r[i - 1].clearance_in, r[i].clearance_in),
          descentDeg: mix(r[i - 1].descentDeg, r[i].descentDeg),
          margin: Math.min(r[i - 1].margin, r[i].margin),
        };
      }
    }
    return r[0];
  }

  /** The tube nearest this pose, with the range and FTC bearing to it. */
  nearest(x: number, y: number): { index: number; range_in: number; bearingDeg: number } | null {
    if (!this.flowers.length) return null;
    let best = -1, bestD = Infinity;
    this.flowers.forEach((f, i) => {
      const d = Math.hypot(f.x - x, f.y - y);
      if (d < bestD) { bestD = d; best = i; }
    });
    const f = this.flowers[best];
    return { index: best, range_in: bestD, bearingDeg: (Math.atan2(f.y - y, f.x - x) * 180) / Math.PI };
  }
}
