/**
 * The fixed-speed shot table: hood angle against (range, radial velocity).
 *
 * Generated by tools/hoodtable.ts. The wheel is held at one speed all match, so the flywheel
 * is no longer in the control loop -- it never has to reach a new speed, never lags on the way
 * there, and its +-107 rpm-a-count tachometer stops deciding whether a shot is allowed. The
 * hood does the aiming instead, and a hood is a servo: commanded to a position.
 *
 * The robot's own velocity is not cancelled here. It is an AXIS of the table, because it is
 * part of the launch condition -- exit speed S at hood theta plus radial speed v leaves the
 * ball with horizontal S*cos(theta) + v and vertical S*sin(theta).
 */

export interface HoodCell {
  /** Hood angles that thread the mouth, and the one to command. */
  lo: number;
  mid: number;
  hi: number;
  /** One sigma of hood error from all launch scatter, degrees. */
  sigmaHood: number;
  descentDeg: number;
  arrival_mps: number;
  pStay: number;
}

export class HoodTable {
  /** rpm the whole table assumes. The wheel sits here and does not move. */
  readonly fixedRpm: number;
  private readonly ranges: number[];
  private readonly vels: number[];
  private readonly at = new Map<string, HoodCell>();

  constructor(fixedRpm: number, cells: (HoodCell & { range_in: number; v_mps: number })[]) {
    this.fixedRpm = fixedRpm;
    for (const c of cells) this.at.set(`${c.range_in}|${c.v_mps}`, c);
    this.ranges = [...new Set(cells.map((c) => c.range_in))].sort((a, b) => a - b);
    this.vels = [...new Set(cells.map((c) => c.v_mps))].sort((a, b) => a - b);
  }

  static fromCsv(csv: string): HoodTable {
    let fixedRpm = 0;
    const cells: (HoodCell & { range_in: number; v_mps: number })[] = [];
    for (const line of csv.trim().split(/\r?\n/)) {
      const rpm = /^#\s*fixed_rpm=(\d+(?:\.\d+)?)/.exec(line);
      if (rpm) {
        fixedRpm = Number(rpm[1]);
        continue;
      }
      if (line.startsWith('#') || line.startsWith('range_in')) continue;
      const [r, v, lo, mid, hi, sig, desc, arr, ps] = line.split(',').map(Number);
      if (!Number.isFinite(r) || !Number.isFinite(v)) continue;
      cells.push({
        range_in: r, v_mps: v, lo, mid, hi, sigmaHood: sig,
        descentDeg: desc, arrival_mps: arr, pStay: ps,
      });
    }
    return new HoodTable(fixedRpm, cells);
  }

  get isEmpty(): boolean {
    return this.at.size === 0;
  }

  /** Bracketing pair from an axis, or null past either end. */
  private static span(axis: number[], x: number): [number, number, number] | null {
    if (!axis.length || x < axis[0] || x > axis[axis.length - 1]) return null;
    for (let i = 1; i < axis.length; i++) {
      if (x <= axis[i]) {
        const t = (x - axis[i - 1]) / (axis[i] - axis[i - 1] || 1);
        return [axis[i - 1], axis[i], t];
      }
    }
    return [axis[axis.length - 1], axis[axis.length - 1], 0];
  }

  /**
   * The shot from here, moving like this -- or null, which means there is not one.
   *
   * Null is a real answer and the caller must respect it: the table has holes where the
   * geometry has no solution, such as closing on the hive faster than the ball's own
   * horizontal speed at short range. A missing corner makes the whole cell null rather than
   * being interpolated around, because halfway between a solution and nothing is nothing.
   */
  lookup(range_in: number, vRadial_mps: number): HoodCell | null {
    const R = HoodTable.span(this.ranges, range_in);
    const V = HoodTable.span(this.vels, vRadial_mps);
    if (!R || !V) return null;
    const [r0, r1, tr] = R;
    const [v0, v1, tv] = V;
    const c00 = this.at.get(`${r0}|${v0}`);
    const c01 = this.at.get(`${r0}|${v1}`);
    const c10 = this.at.get(`${r1}|${v0}`);
    const c11 = this.at.get(`${r1}|${v1}`);
    if (!c00 || !c01 || !c10 || !c11) return null;

    const mix = (a: number, b: number, c: number, d: number) =>
      (1 - tr) * ((1 - tv) * a + tv * b) + tr * ((1 - tv) * c + tv * d);
    // INTERPOLATE the band, do not take its worst corner.
    //
    // Worst-corner looks conservative and is simply wrong: the band slides as range and speed
    // change, so neighbouring cells often do not overlap at all -- 59-62 next to 63-66 -- and
    // max(lo) > min(hi) is an EMPTY interval. The hood can then never be inside it and the
    // robot never fires. It did not fire once, in any case, until this line changed.
    return {
      lo: mix(c00.lo, c01.lo, c10.lo, c11.lo),
      hi: mix(c00.hi, c01.hi, c10.hi, c11.hi),
      mid: mix(c00.mid, c01.mid, c10.mid, c11.mid),
      sigmaHood: Math.max(c00.sigmaHood, c01.sigmaHood, c10.sigmaHood, c11.sigmaHood),
      descentDeg: mix(c00.descentDeg, c01.descentDeg, c10.descentDeg, c11.descentDeg),
      arrival_mps: mix(c00.arrival_mps, c01.arrival_mps, c10.arrival_mps, c11.arrival_mps),
      pStay: Math.min(c00.pStay, c01.pStay, c10.pStay, c11.pStay),
    };
  }
}
