package org.firstinspires.ftc.teamcode.control;

import org.firstinspires.ftc.teamcode.config.RobotConstants;
import org.firstinspires.ftc.teamcode.util.Units;

/**
 * Where to aim, from a camera that is usually not looking at the goal.
 *
 * THIS REPLACES AN ORACLE. The old {@code SimTargetProvider} read the world's `game` block:
 * exact bearing, exact range, exact "is the mouth still facing me", and the precise instant
 * the HIVE went over -- with no noise, no latency, no field of view, and no way to be
 * invalid. Nothing on a Control Hub can supply any of that. Every aiming result this project
 * has ever measured was measured on top of it (docs/PHYSICS.md 6, docs/LOCALIZATION.md), and
 * this class is the thing that takes it away.
 *
 * What is left is a detection that arrives late, at the camera's frame rate rather than the
 * loop's, and stops arriving whenever the tag is not decodable. Three states come out of it,
 * and only one of them may fire:
 *
 *   FRESH   a detection within `maxFireAgeS`: aim on it, fire on it.
 *   HELD    none for a moment, but there was one: aim on the fix carried forward by
 *           odometry, DO NOT FIRE. A shot solved off a fix a third of a second old is solved
 *           off where the goal WAS -- and that window is exactly where a TIP lives.
 *   LOST    nothing recent enough to carry: sweep the turret and go and find the tag.
 *
 * The fix is carried the cheap way. A detection is turned into a FIELD-FRAME POINT once, and
 * the bearing and range are re-derived from the localizer's current pose every loop after
 * that. Two trig calls, no target model, no field geometry baked into the robot at all -- and
 * it degrades exactly the way the odometry does, which is the honest failure mode. With no
 * localizer fitted (`tryGet` returns null on a bare hub) there is nothing to carry it with,
 * so a fix is worth only as long as the robot stays still, and `holdS` is clamped to
 * `maxFireAgeS`: no dead reckoning, no pretending.
 *
 * MIRRORED by packages/core/src/robot/tagTarget.ts. The simulator's own brain answers "where
 * is the goal" with the same three states off the same detections, or the sim measures one
 * robot and the hub flies another.
 */
public class TagTargetProvider implements TargetProvider {
    private final TagCamera cam;
    private final Localizer loc;
    private final double holdS;
    private final double maxFireAgeS;
    private final double scanRateDps;
    private final double turretMinDeg;
    private final double turretMaxDeg;
    /**
     * THE PANEL IS NOT THE MOUTH. The am-5888 the camera decodes sits about 10 in from the
     * CELL mouth on the same rocker, so a fix taken at face value aims at the wrong thing.
     * Both are rigid on the rocker and the rocker is bistable, so the correction has exactly
     * two field-frame values and the TAG ID says which -- docs/LOCALIZATION.md's "the tag ID
     * is the rocker state sensor", turned into arithmetic. Generated by tools/tagoffsets.ts;
     * the FTC +Y term is zero because both parts sit on the pivot axis.
     */
    private final double mouthDxA;
    private final double mouthDxB;
    /** Which way the up CELL opens along FTC +X in each state. A TIP flips it. */
    private final double facingA;
    private final double facingB;
    /**
     * WHERE THE HIVE IS, per rocker state, FTC inches. The HIVE is bolted to the floor: only
     * which of its two CELLs is up ever changes. So a robot with odometry and no tag can still
     * aim at it -- what it cannot do on its own is tell which of these two applies.
     */
    private final double mouthFromAnchorA;
    private final double mouthFromAnchorB;
    private final double anchorAlpha;
    /**
     * THE HIVE'S PIVOT, AS THE ROBOT BELIEVES IT. Seeded from the surveyed prior and replaced
     * by the robot's own estimate at the first decode: measured mouth minus the rigid
     * pivot->mouth offset IS the pivot, in field coordinates. It is the right thing to track
     * because a TIP swings the CELLs about it and leaves it alone -- so one sighting of either
     * CELL locates both.
     */
    private double anchorX;
    private double anchorY;
    private boolean anchorSeen = false;
    private final boolean fireOnOdometry;
    /** Which CELL is up at the buzzer. True at the start, an assumption after any TIP. */
    private final int startId;
    /** Has a tag EVER been decoded? Until it has, the rocker state is that assumption. */
    private boolean seenTag = false;
    private boolean fromOdometry = false;

    /** The last detection as a point on the field, and when it was taken. */
    private double fixX = 0;
    private double fixY = 0;
    private double fixFacingX = 0;
    private int fixId = 0;
    private double fixT = -1e9;

    /** Live answers, recomputed once per {@link #update()} so every reader agrees. */
    private double azimuthDeg = 0;
    private double rangeIn = 0;
    private double ageS = Double.POSITIVE_INFINITY;
    private boolean valid = false;
    private boolean fresh = false;
    private boolean scanning = true;

    private double scanDeg = 0;
    private double scanDir = 1;
    private double lastT = -1;

    public TagTargetProvider(TagCamera cam, Localizer loc, double holdS, double maxFireAgeS,
                             double scanRateDps, double turretMinDeg, double turretMaxDeg,
                             double mouthDxA, double mouthDxB, double facingA, double facingB,
                             double anchorPriorX, double anchorPriorY,
                             double mouthFromAnchorA, double mouthFromAnchorB, double anchorAlpha,
                             boolean fireOnOdometry, int startId) {
        this.anchorX = anchorPriorX;
        this.anchorY = anchorPriorY;
        this.mouthFromAnchorA = mouthFromAnchorA;
        this.mouthFromAnchorB = mouthFromAnchorB;
        this.anchorAlpha = anchorAlpha;
        this.fireOnOdometry = fireOnOdometry;
        this.startId = startId;
        this.mouthDxA = mouthDxA;
        this.mouthDxB = mouthDxB;
        this.facingA = facingA;
        this.facingB = facingB;
        this.cam = cam;
        this.loc = loc;
        // NO ODOMETRY, NO CARRY. Holding a fix through a blind patch is dead reckoning, and
        // dead reckoning without a localizer is just hoping.
        this.holdS = loc == null ? maxFireAgeS : Math.max(holdS, maxFireAgeS);
        this.maxFireAgeS = maxFireAgeS;
        this.scanRateDps = scanRateDps;
        this.turretMinDeg = turretMinDeg;
        this.turretMaxDeg = turretMaxDeg;
    }

    /**
     * Call once per loop, before the aim reads anything.
     *
     * The clock is the CAMERA's, not the OpMode's: a detection is stamped with the time its
     * photons left, and comparing that against a timer started at init is comparing two
     * different zeros. On the hub both come off `System.nanoTime()`; here both come off the
     * world. One clock, or the age -- which is the only thing this class decides anything
     * with -- is meaningless.
     */
    public void update() {
        double t = cam == null ? 0 : cam.getTimeS();
        double dt = lastT < 0 ? 0.02 : Math.max(1e-3, Math.min(0.2, t - lastT));
        lastT = t;

        if (cam != null && cam.hasFix() && cam.getSampleTimeS() > fixT) {
            // REPLACED, NEVER BLENDED, which is what docs/LOCALIZATION.md phase 5 asks for on
            // an ID change and the reason there is no ID check here to forget: the two CELLs
            // sit 14 in apart on opposite sides of the pivot, and averaging a fix on one with
            // a fix on the other aims at the rocker between them. Newest detection wins.
            double lx = loc == null ? 0 : loc.getX();
            double ly = loc == null ? 0 : loc.getY();
            double head = loc == null ? 0 : loc.getHeadingDeg();
            double b = Math.toRadians(head + cam.getBearingDeg());
            // THE TAG, then the MOUTH. The ID picks which of the two rigid corrections
            // applies, so the same detection at the same place means two different aim points
            // depending on which way the rocker is lying -- which is the whole point of the
            // IDs being distinct.
            int id = cam.getId();
            fixX = lx + cam.getRangeIn() * Math.cos(b) + (id == RobotConstants.TAG_ID_CELL_B ? mouthDxB : mouthDxA);
            fixY = ly + cam.getRangeIn() * Math.sin(b);
            fixFacingX = id == RobotConstants.TAG_ID_CELL_B ? facingB : facingA;
            fixId = id;
            seenTag = true;

            // AND TRACK THE HIVE ITSELF. The measured mouth minus the rigid pivot->mouth
            // offset is the pivot, measured. From then on the robot aims at a HIVE it has
            // located for itself; the surveyed prior was only ever somewhere to start.
            double off = id == RobotConstants.TAG_ID_CELL_B ? mouthFromAnchorB : mouthFromAnchorA;
            double ax = fixX - off;
            double ay = fixY;
            double a = anchorSeen ? Units.clamp(anchorAlpha, 0, 1) : 1;
            anchorX += a * (ax - anchorX);
            anchorY += a * (ay - anchorY);
            anchorSeen = true;
            fixT = cam.getSampleTimeS();
        }

        boolean have = fixT > -1e8;
        ageS = have ? Math.max(0, t - fixT) : Double.POSITIVE_INFINITY;
        valid = have && ageS <= holdS;
        fresh = have && ageS <= maxFireAgeS;

        if (!valid) {
            // ODOMETRY. The tag is gone; the HIVE is not. It sits at a field constant, so a
            // pose still gives a bearing and a range, and the robot keeps working through a
            // vision dropout instead of standing still hunting for it. Pointing the turret at
            // where the goal must be is also the fastest way to get the tag back, because the
            // camera rides the turret.
            //
            // WHAT ODOMETRY CANNOT SEE IS THE ROCKER. Until a tag has been decoded once, the
            // state below is the one the match started on -- correct at the buzzer, quietly
            // wrong from the first TIP nobody watched. That is why seenTag gates the SHOT and
            // not the AIM: pointing at the wrong CELL costs nothing, firing into it costs a
            // ball and moves the HIVE for the other alliance.
            if (loc != null) {
                // FROM THE TRACKED PIVOT, not a baked goal position. Before the first
                // sighting that is the surveyed prior; after it, it is the robot's own
                // estimate, and a TIP only changes which offset gets added to it.
                int stateId = seenTag ? fixId : startId;
                double mx = anchorX + (stateId == RobotConstants.TAG_ID_CELL_B ? mouthFromAnchorB : mouthFromAnchorA);
                double my = anchorY;
                double face = stateId == RobotConstants.TAG_ID_CELL_B ? facingB : facingA;
                double dx = mx - loc.getX();
                double dy = my - loc.getY();
                rangeIn = Math.hypot(dx, dy);
                azimuthDeg = Units.wrapDeg(Math.toDegrees(Math.atan2(dy, dx)) - loc.getHeadingDeg());
                scanDeg = Units.clamp(azimuthDeg, turretMinDeg, turretMaxDeg);
                fixX = mx;
                fixY = my;
                fixFacingX = face;
                fixId = stateId;
                valid = true;
                fresh = fireOnOdometry && seenTag;
                scanning = false;
                fromOdometry = true;
                return;
            }

            // SEARCH, for a robot with no pose at all -- `tryGet` returns no localizer on a
            // bare hub. The camera rides the turret, so with nothing to point at nothing is
            // ever found. Sweep the travel until a tag lands in the lens.
            fromOdometry = false;
            scanDeg += scanDir * scanRateDps * dt;
            if (scanDeg >= turretMaxDeg) { scanDeg = turretMaxDeg; scanDir = -1; }
            else if (scanDeg <= turretMinDeg) { scanDeg = turretMinDeg; scanDir = 1; }
            azimuthDeg = scanDeg;
            rangeIn = 0;
            scanning = true;
            return;
        }

        double dx = fixX - (loc == null ? 0 : loc.getX());
        double dy = fixY - (loc == null ? 0 : loc.getY());
        // With no localizer the fix is held in the robot's own frame instead, because there is
        // no pose to difference against -- correct only while the robot is parked, which is
        // the same window holdS was clamped to above.
        if (loc == null) {
            azimuthDeg = Units.wrapDeg(cam == null ? 0 : cam.getBearingDeg());
            rangeIn = cam == null ? 0 : cam.getRangeIn();
        } else {
            rangeIn = Math.hypot(dx, dy);
            azimuthDeg = Units.wrapDeg(Math.toDegrees(Math.atan2(dy, dx)) - loc.getHeadingDeg());
        }
        // Park the sweep where the target is, so losing the lock resumes the search from the
        // last place the tag was rather than from wherever the sweep had wandered to before.
        scanDeg = Units.clamp(azimuthDeg, turretMinDeg, turretMaxDeg);
        scanning = false;
        fromOdometry = false;
    }

    /** Always a bearing worth pointing at: the fix, the carried fix, or the search sweep. */
    @Override public double getAzimuthDeg() { return azimuthDeg; }

    @Override public double getRangeIn() { return rangeIn; }

    /**
     * 180 -- unknown, and unshootable -- until the camera has ever seen the tag.
     *
     * COMPUTED, not measured, and that is the better answer. The pipeline does return a tag
     * yaw, and it is the worst-conditioned axis of an AprilTag pose by an order: 6 deg of
     * sigma against 0.5 on bearing. Knowing which CELL is up IS knowing which way its mouth
     * opens, so the ID plus the baked normal gives the same fact exactly and for free, and
     * the noisiest number the camera produces stops gating shots.
     */
    @Override public double getOpenAngleDeg() {
        if (fixT <= -1e8 || fixFacingX == 0 || loc == null) return 180;
        double dx = loc.getX() - fixX;
        double dy = loc.getY() - fixY;
        double d = Math.hypot(dx, dy);
        if (d < 1e-6) return 0;
        return Math.toDegrees(Math.acos(Units.clamp((dx * fixFacingX) / d, -1, 1)));
    }

    /**
     * THE REPLACEMENT FOR THE ORACLE'S `hiveTipping`, and it is not a rename.
     *
     * The world used to tell the robot the instant the rocker moved. A camera is told nothing
     * -- it just stops decoding -- so a TIP, an occlusion, driving out of the lens and simply
     * looking the wrong way all arrive as one fact: the fix is older than the shooter can use.
     * Holding fire is the right answer to every one of them, so one gate covers all four, and
     * the robot no longer needs to be handed a state transition it could never observe.
     */
    @Override public boolean isTipping() { return valid && !fresh; }

    /** A fix exists and is recent enough to AIM by. False means the turret is searching. */
    @Override public boolean isValid() { return valid; }

    /** Recent enough to FIRE on. Implies {@link #isValid()}. */
    public boolean isFresh() { return fresh; }

    public boolean isScanning() { return scanning; }

    public double getAgeS() { return ageS; }

    /** The aim came from the localizer and the baked HIVE position, not from a detection. */
    public boolean isFromOdometry() { return fromOdometry; }

    /** A tag has been seen at least once, so the rocker state is observed, not assumed. */
    public boolean isStateFromTag() { return seenTag; }

    /** The HIVE's pivot as the robot believes it, FTC inches. Telemetry. */
    public double getAnchorX() { return anchorX; }
    public double getAnchorY() { return anchorY; }

    /** True once the pivot is the robot's own estimate rather than the surveyed prior. */
    public boolean isAnchorFromTag() { return anchorSeen; }

    /** 1 = CELL A, 2 = CELL B, 0 before the first detection. */
    public int getId() { return fixId; }
}
