package org.firstinspires.ftc.teamcode.config;

import org.firstinspires.ftc.teamcode.control.ShotTable;

/**
 * One robot description, two consumers. The numbers come from config/robot.json; on the
 * hub they arrive as RobotConstants, generated by tools/genconstants.mjs so that nothing
 * has to parse a file on an Android device at match time.
 *
 * Regenerate after editing robot.json:  npm run tool -- tools/genconstants.mjs
 */
public class RobotConfig {
    public final String name = RobotConstants.NAME;

    // hardware names
    public final String FL = RobotConstants.HW_FL;
    public final String FR = RobotConstants.HW_FR;
    public final String BL = RobotConstants.HW_BL;
    public final String BR = RobotConstants.HW_BR;
    public final String INTAKE = RobotConstants.HW_INTAKE;
    public final String TRANSFER = RobotConstants.HW_TRANSFER;
    public final String FLYWHEEL = RobotConstants.HW_FLYWHEEL;
    public final String TURRET = RobotConstants.HW_TURRET;
    public final String HOOD = RobotConstants.HW_HOOD;
    public final String GATE = RobotConstants.HW_GATE;
    public final String IMU = RobotConstants.HW_IMU;

    // drivetrain
    public final double wheelRadiusIn = RobotConstants.WHEEL_RADIUS_M * 39.3700787;
    public final double driveTicksPerRev = RobotConstants.DRIVE_TICKS_PER_REV;
    public final boolean flReversed = RobotConstants.FL_REVERSED;
    public final boolean frReversed = RobotConstants.FR_REVERSED;
    public final boolean blReversed = RobotConstants.BL_REVERSED;
    public final boolean brReversed = RobotConstants.BR_REVERSED;

    // mechanisms
    public final double cycleTimeS = RobotConstants.CYCLE_TIME_S;
    public final double feedPulseS = RobotConstants.FEED_PULSE_S;
    public final boolean gateEnabled = RobotConstants.GATE_ENABLED;
    public final double gateOpen = RobotConstants.GATE_OPEN;
    public final double gateClosed = RobotConstants.GATE_CLOSED;
    public final int hopperCapacity = RobotConstants.HOPPER_CAPACITY;

    public final double turretMinDeg = RobotConstants.TURRET_MIN_DEG;
    public final double turretMaxDeg = RobotConstants.TURRET_MAX_DEG;
    public final double turretSpeedDps = RobotConstants.TURRET_SPEED_DPS;
    public final double turretTicksPerDeg = RobotConstants.TURRET_TICKS_PER_DEG;

    public final double hoodMinDeg = RobotConstants.HOOD_MIN_DEG;
    public final double hoodMaxDeg = RobotConstants.HOOD_MAX_DEG;
    public final double hoodTolDeg = RobotConstants.HOOD_TOL_DEG;
    public final double velFilterAlpha = RobotConstants.VEL_FILTER_ALPHA;

    public final double flywheelTicksPerRev = RobotConstants.FLYWHEEL_TICKS_PER_REV;
    public final double flywheelTolRpm = RobotConstants.FLYWHEEL_TOL_RPM;
    public final double flywheelMinRpmFrac = RobotConstants.FLYWHEEL_MIN_RPM_FRAC;
    public final int flywheelReadySteps = RobotConstants.FLYWHEEL_READY_STEPS;
    public final int flywheelRpmFilterFrames = RobotConstants.FLYWHEEL_RPM_FILTER_FRAMES;
    public final double flywheelMinLandProb = RobotConstants.FLYWHEEL_MIN_LAND_PROB;
    public final double flywheelYawScatterDeg = RobotConstants.FLYWHEEL_YAW_SCATTER_DEG;
    public final double flywheelMaxRpm = RobotConstants.FLYWHEEL_MAX_RPM;

    // feedforward for FlywheelGate: power = (kS + kV*rpm)*(12/V) + kP*err
    public final double flywheelKs = RobotConstants.FLYWHEEL_KS;
    public final double flywheelKv = RobotConstants.FLYWHEEL_KV;
    public final double flywheelKp = RobotConstants.FLYWHEEL_KP;

    /** Exit speed a given flywheel RPM produces: v = k * omega * r. */
    public double exitSpeedFor(double rpm) {
        return RobotConstants.FLYWHEEL_K * RobotConstants.FLYWHEEL_R_M * (rpm * 2 * Math.PI / 60.0);
    }

    public ShotTable shotTable() {
        return new ShotTable(ShotTableData.RANGE_IN, ShotTableData.HOOD_POS, ShotTableData.RPM, ShotTableData.MARGIN);
    }
}
