package org.firstinspires.ftc.teamcode.config;

/**
 * GENERATED by tools/genconstants.mjs from config/robot.json -- do not edit by hand.
 * Re-run after changing the robot description:  node tools/genconstants.mjs
 */
public final class RobotConstants {
    private RobotConstants() { }

    public static final String NAME = "box-v1";

    // ---- hardware names (must match the Robot Controller configuration) ----
    public static final String HW_FL = "motor0";
    public static final String HW_FR = "motor1";
    public static final String HW_BL = "motor2";
    public static final String HW_BR = "motor3";
    public static final String HW_INTAKE = "motor4";
    public static final String HW_TRANSFER = "motor5";
    public static final String HW_FLYWHEELA = "motor6";
    public static final String HW_FLYWHEELB = "motor7";
    public static final String HW_TURRET = "servo2";
    public static final String HW_HOOD = "servo0";
    public static final String HW_GATE = "servo1";
    public static final String HW_IMU = "imu";

    // ---- drivetrain ----
    public static final double WHEEL_RADIUS_M = 0.048;
    public static final double DRIVE_TICKS_PER_REV = 537.7;
    public static final boolean FL_REVERSED = true;
    public static final boolean FR_REVERSED = false;
    public static final boolean BL_REVERSED = true;
    public static final boolean BR_REVERSED = false;

    // ---- mechanisms ----
    /** The knob this whole project exists to explore. */
    public static final double CYCLE_TIME_S = 1;
    public static final double FEED_PULSE_S = 0.25;
    public static final boolean GATE_ENABLED = true;
    public static final double GATE_OPEN = 1;
    public static final double GATE_CLOSED = 0;
    public static final int HOPPER_CAPACITY = 4;

    public static final double TURRET_MIN_DEG = -270;
    public static final double TURRET_MAX_DEG = 270;
    public static final double TURRET_SPEED_DPS = 261;
    public static final double TURRET_TICKS_PER_DEG = 8;
    /** Muzzle distance from the turret axis along the shot line, m. The lever arm of omega x r in ShotLead.muzzleVelocity(). */
    public static final double MUZZLE_OFFSET_M = 0.12;

    public static final double HOOD_MIN_DEG = 40;
    public static final double HOOD_MAX_DEG = 80;
    public static final double HOOD_TOL_DEG = 2;
    public static final double VEL_FILTER_ALPHA = 0.25;

    public static final double FLYWHEEL_TICKS_PER_REV = 28;
    public static final double FLYWHEEL_FREE_RPM = 6000;
    public static final double FLYWHEEL_MAX_RPM = 6000;
    public static final double FLYWHEEL_TOL_RPM = 60;
    public static final double FLYWHEEL_MIN_RPM_FRAC = 0.97;
    public static final int FLYWHEEL_READY_STEPS = 3;
    /** MEASURED by tools/flywheeltune.ts --ff, not guessed */
    public static final double FLYWHEEL_KS = 0.0049;
    /** MEASURED duty per RPM at 12 V */
    public static final double FLYWHEEL_KV = 0.000167509;
    /** proportional trim on RPM error */
    public static final double FLYWHEEL_KP = 0.0008;
    /** exit efficiency: v_exit = k * omega * r */
    public static final double FLYWHEEL_K = 0.45;
    public static final double FLYWHEEL_R_M = 0.048;
    /** loops of moving average over getVelocity(). One reading is quantised to about 107 RPM on a direct-driven 28-tick encoder */
    public static final int FLYWHEEL_RPM_FILTER_FRAMES = 6;
    /** refuse the shot below this CALIBRATED chance of landing. 0 disables the probability gate and leaves the RPM window alone */
    public static final double FLYWHEEL_MIN_LAND_PROB = 0.7;
    /** one sigma of launch bearing scatter */
    public static final double FLYWHEEL_YAW_SCATTER_DEG = 1;

    // ---- tag target (TagTargetProvider) ----
    /** how long a fix may be carried forward on odometry before the target counts as lost and the turret starts sweeping */
    public static final double TAG_HOLD_S = 0.75;
    /** how old a fix may be and still be SHOT on. This is what replaced the oracle hiveTipping flag: a rocker going over blinds the camera, the fix ages past this, and the robot holds fire without ever being told the HIVE moved */
    public static final double TAG_MAX_FIRE_AGE_S = 0.25;
    /** turret sweep rate while searching for the tag. No field geometry is baked in, so the robot re-acquires from wherever it actually is */
    public static final double TAG_SCAN_RATE_DPS = 120;

    // ---- tag -> CELL mouth, per rocker state (GENERATED by tools/tagoffsets.ts) ----
    /** the tag on CELL A. Phase 0 of docs/LOCALIZATION.md: the REAL ids are not recorded anywhere and must be looked up */
    public static final int TAG_ID_CELL_A = 1;
    /** the tag on CELL B */
    public static final int TAG_ID_CELL_B = 2;
    /** add to the tag field X to get the mouth, with CELL A up. The FTC Y term is zero: both parts sit on the pivot axis */
    public static final double TAG_MOUTH_DX_A_IN = 2.7848;
    /** the same, with CELL B up. Opposite sign, because the rocker is on the other stop */
    public static final double TAG_MOUTH_DX_B_IN = -2.7845;
    /** which way the up CELL opens along FTC +X with CELL A up. A TIP flips this, which is why a robot that was square onto the goal is behind it afterwards */
    public static final int MOUTH_FACING_X_A = 1;
    /** the same, with CELL B up */
    public static final int MOUTH_FACING_X_B = -1;
    /** set from robot.json -> alliance */
    public static final boolean ALLIANCE_IS_RED = true;
    /** surveyed pivot, FTC X. A PRIOR: replaced by the robot own estimate at the first sighting */
    public static final double HIVE_ANCHOR_X_IN = 0;
    /** surveyed pivot, FTC Y */
    public static final double HIVE_ANCHOR_Y_IN = -12.74;
    /** pivot -> up CELL mouth with CELL A up. Rigid: a property of the HIVE, not of the field */
    public static final double MOUTH_FROM_ANCHOR_X_A_IN = 15.6775;
    /** the same with CELL B up -- the far side of the same pivot */
    public static final double MOUTH_FROM_ANCHOR_X_B_IN = -15.6775;
    /** one-pole on the tracked pivot across sightings */
    public static final double HIVE_ANCHOR_ALPHA = 0;
    /** may a shot be taken with no tag in view, on odometry alone? Never before a tag has been seen at least once, because until then the rocker state is an assumption */
    public static final boolean FIRE_ON_ODOMETRY = true;
    /** the opposing HIVE pivot, FTC X */
    public static final double OBSTACLE_X_IN = 0;
    /** the opposing HIVE pivot, FTC Y */
    public static final double OBSTACLE_Y_IN = 12.76;
    /** how far their CELL mouths reach from that pivot */
    public static final double OBSTACLE_RADIUS_IN = 22.0705;
    /** half a CELL width, along the pivot axis */
    public static final double OBSTACLE_HALF_WIDTH_IN = 10;
    /** fraction of each fix position disagreement absorbed. A gain, not a jump: a fix carries 4% of range */
    public static final double FUSE_GAIN = 0.15;
    /** the same off the tag yaw, which is the worst axis of an AprilTag pose by an order */
    public static final double FUSE_HEADING_GAIN = 0.05;
    /** refuse a fix that disagrees by more than this: a misread, not drift */
    public static final double FUSE_REJECT_OVER_IN = 36;
}
