package org.firstinspires.ftc.teamcode.config;

/**
 * GENERATED by tools/genconstants.mjs from config/robot.json -- do not edit by hand.
 * Re-run after changing the robot description:  node tools/genconstants.mjs
 */
public final class RobotConstants {
    private RobotConstants() { }

    public static final String NAME = "box-v1";

    // ---- hardware names (must match the Robot Controller configuration) ----
    public static final String HW_FL = "motor0";
    public static final String HW_FR = "motor1";
    public static final String HW_BL = "motor2";
    public static final String HW_BR = "motor3";
    public static final String HW_INTAKE = "motor4";
    public static final String HW_TRANSFER = "motor5";
    public static final String HW_FLYWHEEL = "motor6";
    public static final String HW_TURRET = "motor7";
    public static final String HW_HOOD = "servo0";
    public static final String HW_GATE = "servo1";
    public static final String HW_IMU = "imu";

    // ---- drivetrain ----
    public static final double WHEEL_RADIUS_M = 0.048;
    public static final double DRIVE_TICKS_PER_REV = 537.7;
    public static final boolean FL_REVERSED = true;
    public static final boolean FR_REVERSED = false;
    public static final boolean BL_REVERSED = true;
    public static final boolean BR_REVERSED = false;

    // ---- mechanisms ----
    /** The knob this whole project exists to explore. */
    public static final double CYCLE_TIME_S = 1.5;
    public static final double FEED_PULSE_S = 0.25;
    public static final boolean GATE_ENABLED = true;
    public static final double GATE_OPEN = 1;
    public static final double GATE_CLOSED = 0;
    public static final int HOPPER_CAPACITY = 6;

    public static final double TURRET_MIN_DEG = -120;
    public static final double TURRET_MAX_DEG = 120;
    public static final double TURRET_SPEED_DPS = 180;
    public static final double TURRET_TICKS_PER_DEG = 8;

    public static final double HOOD_MIN_DEG = 30;
    public static final double HOOD_MAX_DEG = 85;
    public static final double HOOD_TOL_DEG = 2;

    public static final double FLYWHEEL_TICKS_PER_REV = 28;
    public static final double FLYWHEEL_FREE_RPM = 6000;
    public static final double FLYWHEEL_MAX_RPM = 6000;
    public static final double FLYWHEEL_TOL_RPM = 60;
    public static final double FLYWHEEL_MIN_RPM_FRAC = 0.97;
    public static final int FLYWHEEL_READY_STEPS = 3;
    /** MEASURED by tools/flywheeltune.ts --ff, not guessed */
    public static final double FLYWHEEL_KS = 0.00442;
    /** MEASURED duty per RPM at 12 V */
    public static final double FLYWHEEL_KV = 0.000164698;
    /** proportional trim on RPM error */
    public static final double FLYWHEEL_KP = 0.0008;
    /** exit efficiency: v_exit = k * omega * r */
    public static final double FLYWHEEL_K = 0.45;
    public static final double FLYWHEEL_R_M = 0.048;
    /** loops of moving average over getVelocity(). One reading is quantised to about 107 RPM on a direct-driven 28-tick encoder */
    public static final int FLYWHEEL_RPM_FILTER_FRAMES = 6;
    /** refuse the shot below this CALIBRATED chance of landing. 0 disables the probability gate and leaves the RPM window alone */
    public static final double FLYWHEEL_MIN_LAND_PROB = 0.85;
    /** one sigma of launch bearing scatter */
    public static final double FLYWHEEL_YAW_SCATTER_DEG = 1;
}
