package org.firstinspires.ftc.teamcode.config;

/**
 * GENERATED by tools/genconstants.mjs from java/teamcode/assets/shottable.csv,
 * which tools/shottable.ts produces for the current robot. Do not edit by hand.
 *
 * 31 ranges. The solver runs on a laptop; the hub only interpolates.
 */
public final class ShotTableData {
    private ShotTableData() { }

    public static final double[] RANGE_IN = { 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 78, 82, 86, 90, 94, 98, 102, 106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150 };
    public static final double[] HOOD_POS = { 0.8333, 0.8, 0.7333, 0.7, 0.7, 0.6667, 0.6333, 0.6, 0.5667, 0.5667, 0.5, 0.5, 0.7667, 0.7333, 0.7333, 0.7, 0.5, 0.6667, 0.2667, 0.2333, 0.2333, 0.4333, 0.2, 0.1667, 0.1667, 0.1667, 0.1667, 0.1333, 0.1, 0.1333, 0.1 };
    public static final double[] RPM      = { 2210, 2238, 2266, 2293, 2321, 2349, 2404, 2404, 2459, 2514, 2514, 2570, 2901, 2901, 2957, 2957, 2791, 3012, 2846, 2901, 2957, 2984, 3012, 3067, 3122, 3150, 3178, 3233, 3288, 3288, 3343 };
    public static final double[] MARGIN   = { 0.05, 0.037, 0.0488, 0.0361, 0.0476, 0.0353, 0.0345, 0.0345, 0.0337, 0.033, 0.033, 0.0323, 0.0286, 0.0286, 0.028, 0.028, 0.0297, 0.0275, 0.0291, 0.0286, 0.028, 0.0185, 0.0275, 0.027, 0.0265, 0.0175, 0.0261, 0.0256, 0.0252, 0.0252, 0.0248 };

    // What the land-probability gate needs. The hub still solves nothing: these are the
    // solver's own outputs per range, and LandProbability turns them into a number.
    public static final double[] SPEED_LO    = { 4.75, 4.875, 4.875, 5, 5, 5.125, 5.25, 5.25, 5.375, 5.5, 5.5, 5.625, 6.375, 6.375, 6.5, 6.5, 6.125, 6.625, 6.25, 6.375, 6.5, 6.625, 6.625, 6.75, 6.875, 7, 7, 7.125, 7.25, 7.25, 7.375 };
    public static final double[] SPEED_HI    = { 5.25, 5.25, 5.375, 5.375, 5.5, 5.5, 5.625, 5.625, 5.75, 5.875, 5.875, 6, 6.75, 6.75, 6.875, 6.875, 6.5, 7, 6.625, 6.75, 6.875, 6.875, 7, 7.125, 7.25, 7.25, 7.375, 7.5, 7.625, 7.625, 7.75 };
    public static final double[] SIGMA_SPEED = { 0.075, 0.07594, 0.09908, 0.07781, 0.07875, 0.07969, 0.08156, 0.08156, 0.08344, 0.08531, 0.08531, 0.08719, 0.15911, 0.15911, 0.16027, 0.16027, 0.09469, 0.16145, 0.09656, 0.09844, 0.11819, 0.10125, 0.10219, 0.10406, 0.123, 0.12381, 0.12462, 0.12624, 0.12788, 0.11156, 0.11344 };
    public static final double[] P_STAY      = { 0.9778, 0.9941, 0.9588, 0.9709, 0.9077, 0.8665, 0.8718, 0.79, 0.8072, 0.7235, 0.6922, 0.65, 0.7817, 0.7371, 0.7602, 0.6677, 0.5676, 0.5963, 0.566, 0.6694, 0.6375, 0.521, 0.5238, 0.5843, 0.5686, 0.4928, 0.4246, 0.4776, 0.5051, 0.3723, 0.4146 };
    /** Half-width of the mouth across the shot line, m, less the ball radius. */
    public static final double[] HALF_LAT_M  = { 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121 };

    // MEASURED score -> frequency mapping from config/landcal.json (tools/landcal.ts).
    // Without it the threshold is a score with a percent sign on it.
    public static final double[] CAL_SCORE    = { 0.490022, 0.698607, 0.801739, 0.816900, 0.847244, 0.946574 };
    public static final double[] CAL_OBSERVED = { 0.839286, 0.892857, 0.964286, 0.964286, 0.964286, 0.964286 };
    /** The best frequency any bin of shots actually achieved. No threshold above this can be met. */
    public static final double CAL_CEILING = 0.964286;
}
