package org.firstinspires.ftc.teamcode.config;

/**
 * GENERATED by tools/genconstants.mjs from java/teamcode/assets/shottable.csv,
 * which tools/shottable.ts produces for the current robot. Do not edit by hand.
 *
 * 31 ranges. The solver runs on a laptop; the hub only interpolates.
 */
public final class ShotTableData {
    private ShotTableData() { }

    public static final double[] RANGE_IN = { 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 78, 82, 86, 90, 94, 98, 102, 106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150 };
    public static final double[] HOOD_POS = { 0.8333, 0.8, 0.7667, 0.7, 0.7333, 0.6333, 0.6, 0.5667, 0.5667, 0.5333, 0.5333, 0.5, 0.4667, 0.5, 0.5, 0.4333, 0.4667, 0.4667, 0.4, 0.4333, 0.4333, 0.4333, 0.4333, 0.4, 0.4, 0.4, 0.3667, 0.3667, 0.3667, 0.3667, 0.3333 };
    public static final double[] RPM      = { 2293, 2293, 2321, 2349, 2404, 2404, 2459, 2514, 2514, 2570, 2570, 2625, 2680, 2680, 2735, 2791, 2791, 2846, 2901, 2929, 2957, 2984, 3039, 3067, 3095, 3150, 3178, 3205, 3260, 3260, 3316 };
    public static final double[] MARGIN   = { 0.0361, 0.0361, 0.0476, 0.0353, 0.0345, 0.0345, 0.0337, 0.033, 0.033, 0.0323, 0.0323, 0.0316, 0.0309, 0.0309, 0.0303, 0.0297, 0.0297, 0.0291, 0.0286, 0.0189, 0.028, 0.0185, 0.0182, 0.027, 0.0179, 0.0175, 0.0261, 0.0172, 0.0169, 0.0169, 0.0167 };

    // What the land-probability gate needs. The hub still solves nothing: these are the
    // solver's own outputs per range, and LandProbability turns them into a number.
    public static final double[] SPEED_LO    = { 5, 5, 5, 5.125, 5.25, 5.25, 5.375, 5.5, 5.5, 5.625, 5.625, 5.75, 5.875, 5.875, 6, 6.125, 6.125, 6.25, 6.375, 6.5, 6.5, 6.625, 6.75, 6.75, 6.875, 7, 7, 7.125, 7.25, 7.25, 7.375 };
    public static final double[] SPEED_HI    = { 5.375, 5.375, 5.5, 5.5, 5.625, 5.625, 5.75, 5.875, 5.875, 6, 6, 6.125, 6.25, 6.25, 6.375, 6.5, 6.5, 6.625, 6.75, 6.75, 6.875, 6.875, 7, 7.125, 7.125, 7.25, 7.375, 7.375, 7.5, 7.5, 7.625 };
    public static final double[] SIGMA_SPEED = { 0.0998, 0.0998, 0.10054, 0.07969, 0.08156, 0.08156, 0.08344, 0.10576, 0.08531, 0.08719, 0.08719, 0.08906, 0.09094, 0.09094, 0.09281, 0.09469, 0.09469, 0.09656, 0.09844, 0.09937, 0.10031, 0.10125, 0.10312, 0.10406, 0.105, 0.10687, 0.10781, 0.10875, 0.11063, 0.11063, 0.1125 };
    public static final double[] P_STAY      = { 0.9955, 0.9807, 0.9573, 0.9306, 0.91, 0.9821, 0.9828, 0.9767, 0.9575, 0.9653, 0.9215, 0.9264, 0.8899, 0.87, 0.8688, 0.7968, 0.8663, 0.8743, 0.7406, 0.8424, 0.8721, 0.8445, 0.8442, 0.8743, 0.8585, 0.8581, 0.8589, 0.8686, 0.868, 0.8569, 0.8745 };
    /** Half-width of the mouth across the shot line, m, less the ball radius. */
    public static final double[] HALF_LAT_M  = { 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121 };

    // MEASURED score -> frequency mapping from config/landcal.json (tools/landcal.ts).
    // Without it the threshold is a score with a percent sign on it.
    public static final double[] CAL_SCORE    = { 0.694315, 0.853862, 0.894562, 0.919816, 0.941808 };
    public static final double[] CAL_OBSERVED = { 0.508475, 0.728814, 0.898305, 0.898305, 0.898305 };
    /** The best frequency any bin of shots actually achieved. No threshold above this can be met. */
    public static final double CAL_CEILING = 0.898305;
}
