/**
 * Write docs/VARIABLES.md from the config files.
 *
 *   node tools/vars.mjs
 *
 * Generated rather than hand-written so the reference cannot drift from the numbers the
 * simulator actually runs on. Every `_source` note travels with its value.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const here = (p) => new URL(p, import.meta.url);
const read = (f) => JSON.parse(readFileSync(here(`../config/${f}`), 'utf8'));
const params = read('params.json');
const robot = read('robot.json');
const motors = read('motors.json');

const IN = 39.3700787;

/** Pull `key` and its `key_source` / `_source` sibling out of an object. */
function rows(obj, keys, path) {
  const out = [];
  for (const k of keys) {
    if (!(k in obj)) continue;
    const v = obj[k];
    const note = obj[`${k}_source`] ?? obj[`_${k}Source`] ?? obj._source ?? '';
    out.push({ path: `${path}.${k}`, value: v, note });
  }
  return out;
}

const fmt = (v) => {
  if (Array.isArray(v)) return `[${v.map(fmt).join(', ')}]`;
  if (typeof v === 'number') return Number.isInteger(v) ? String(v) : String(+v.toPrecision(6));
  return String(v);
};
const short = (s) => String(s).replace(/\s+/g, ' ').trim();

const section = (title, list, extra = () => '') => {
  const lines = [`### ${title}`, '', '| variable | value | also | note |', '|---|---|---|---|'];
  for (const r of list) {
    lines.push(`| \`${r.path}\` | ${fmt(r.value)} | ${extra(r) || ''} | ${short(r.note)} |`);
  }
  lines.push('');
  return lines.join('\n');
};

const inches = (r) => (typeof r.value === 'number' && r.path.endsWith('_m') ? `${(r.value * IN).toFixed(2)} in` : '');

const out = [];
out.push('# Variables');
out.push('');
out.push('GENERATED by `node tools/vars.mjs` from `config/*.json` — do not edit by hand.');
out.push('');
out.push('Everything physical lives in config; nothing is hard-coded in either half. A value');
out.push("whose note says **guess** or **CALIBRATE** has not been measured yet — those are the");
out.push('knobs worth sweeping. The **Tune** tab in the app edits the most consequential ones live.');
out.push('');

// ---------------------------------------------------------------- robot
out.push('## Robot');
out.push('');
out.push(section('Chassis', rows(robot.chassis, ['length_m', 'width_m', 'height_m', 'mass_kg', 'Izz_kgm2', 'cgOffset_m', 'clearance_m'], 'chassis'), inches));
out.push(section('Drivetrain', rows(robot.drivetrain, ['type', 'wheelRadius_m', 'wheelbase_m', 'track_m', 'rollerAngle_deg', 'mu', 'eta', 'rollingRes_N'], 'drivetrain'), inches));

const wheelRows = Object.entries(robot.drivetrain.motors).map(([k, v]) => ({
  path: `drivetrain.motors.${k}`,
  value: `${v.variant}, gear ${v.gearRatio}${v.reversed ? ', reversed' : ''}`,
  note: `${motors.variants[v.variant].freeRpm} rpm free, ${motors.variants[v.variant].ticksPerRev} ticks/rev`,
}));
out.push(section('Drive motors', wheelRows));

out.push(section('Intake', [
  ...rows(robot.intake, ['captureThreshold', 'captureDelay_s', 'length_m', 'speed_mps'], 'intake'),
  { path: 'intake.mouth', value: `${(robot.intake.mouth.width_m * IN).toFixed(1)} x ${(robot.intake.mouth.height_m * IN).toFixed(1)} x ${(robot.intake.mouth.depth_m * IN).toFixed(1)} in`, note: 'capture trigger volume at the front face' },
  { path: 'intake.motor', value: robot.intake.motor.variant, note: `${motors.variants[robot.intake.motor.variant].freeRpm} rpm free` },
], inches));

out.push(section('Hopper and transfer', [
  { path: 'hopper.capacity', value: robot.hopper.capacity, note: 'balls the robot can hold' },
  ...rows(robot.transfer, ['cycleTime_s', 'feedPulse_s', 'feedTransit_s', 'leadLatency_s'], 'transfer'),
  { path: 'transfer.gate', value: `${robot.transfer.gate.enabled ? 'enabled' : 'off'}, open ${robot.transfer.gate.open} / closed ${robot.transfer.gate.closed}`, note: 'servo gate before the wheel' },
]));

// ---------------------------------------------------------------- shooter
out.push('## Shooter');
out.push('');
out.push(section('Turret', [
  ...rows(robot.turret, ['enabled', 'type', 'range_deg', 'speed_dps', 'accel_dps2', 'muzzleOffset_m', 'muzzleHeight_m'], 'turret'),
  { path: 'turret.motor.ticksPerDeg', value: robot.turret.motor.ticksPerDeg, note: `${robot.turret.motor.variant}, gear ${robot.turret.motor.gearRatio}` },
], inches));

out.push(section('Hood', rows(robot.hood, ['enabled', 'angleRange_deg', 'fixedAngle_deg', 'speed_dps', 'tolDeg'], 'hood')));

out.push(section('Flywheel', [
  ...rows(robot.flywheel, ['type', 'I_fly_kgm2', 'r_fly_m', 'k', 'lossFactor', 'maxRpm', 'tolRpm', 'minRpmFrac', 'readySteps', 'minLandProb', 'rpmFilterFrames', 'dragQuad_Nms2', 'coulomb_Nm'], 'flywheel'),
  { path: 'flywheel.motor', value: robot.flywheel.motor.variant, note: `${motors.variants[robot.flywheel.motor.variant].freeRpm} rpm free` },
  { path: 'flywheel.scatter', value: `${robot.flywheel.scatter.angle_deg} deg elev, ${robot.flywheel.scatter.yaw_deg} deg yaw, ${(robot.flywheel.scatter.speedFrac * 100).toFixed(1)}% speed`, note: 'shot-to-shot spread; the main reason shots miss' },
], inches));

out.push('**Derived, not stored:** exit speed `v = k · ω · r_fly`, so at the 6000 rpm ceiling');
out.push(`this robot throws at ${(robot.flywheel.k * robot.flywheel.r_fly_m * ((robot.flywheel.maxRpm * 2 * Math.PI) / 60)).toFixed(1)} m/s.`);
out.push('Each shot costs the wheel `lossFactor · KE_ball / (I · ω)`.');
out.push('');

// ---------------------------------------------------------------- hive
out.push('## Hive');
out.push('');
out.push(section('Rocker', rows(params.hive, ['massKg', 'cgOffset_m', 'Ipivot_kgm2', 'pivotY_m', 'redX_m', 'blueX_m', 'restAngles_deg', 'frictionTorque_Nm', 'damperC_Nms', 'damperEngage_deg', 'limitRestitution', 'ballsToTipOverride'], 'hive'), inches));

const cgR = Math.hypot(params.hive.cgOffset_m[1], params.hive.cgOffset_m[2]);
const restoring = params.hive.massKg * params.env.g * cgR * Math.sin((30.0435 * Math.PI) / 180);
out.push('**Derived, not stored:** the rocker is an over-centre see-saw. At θ = 0 its CG sits');
out.push(`directly above the pivot, so gravity torque is \`m·g·r·sin θ\` — at the ±30.04° stops that is`);
out.push(`**${restoring.toFixed(3)} N·m** holding it down. A ball in the up CELL pushes back with \`m·g·z\`,`);
out.push('where `z` is its horizontal distance from the pivot axis. Measured onset: **12 POLLEN**');
out.push('or **8 NECTAR**, pooling at a 9–10 in lever arm.');
out.push('');

out.push(section('Game elements', [
  { path: 'ball.pollen.d_m', value: params.ball.pollen.d_m, note: params.ball.pollen._source },
  { path: 'ball.pollen.m_kg', value: params.ball.pollen.m_kg, note: '40 on the field' },
  { path: 'ball.nectar.d_m', value: params.ball.nectar.d_m, note: params.ball.nectar._source },
  { path: 'ball.nectar.m_kg', value: params.ball.nectar.m_kg, note: '8 per alliance' },
  ...rows(params.ball, ['Cd', 'clSlope', 'clSMax', 'spinDecay', 'e_foam', 'e_poly', 'e_ball', 'rollMu', 'mu'], 'ball'),
], inches));

out.push(section('Field and environment', rows(params.env, ['rho', 'g', 'tileSize_m', 'tileThick_m', 'fieldInside_m', 'wallGlassTop_m', 'railTop_m', 'tileMu'], 'env'), inches));

// ---------------------------------------------------------------- sensors
//
// These were missing from this document entirely, which is the worst omission it could have
// had: they are the numbers that decide WHAT THE ROBOT KNOWS, and the ones most likely to be
// wrong. `sensors.tag` in particular replaced a block of ground truth, so every guess in it
// is now load-bearing on every aiming result in the repo.
out.push('## What the robot can actually sense');
out.push('');
out.push(section('Odometry', rows(robot.sensors.localizer.noise, ['xy_in', 'heading_deg', 'vel_mps', 'omegaDps'], 'sensors.localizer.noise')));
out.push(section('Tag camera', [
  ...rows(robot.sensors.tag, ['enabled', 'mount', 'fov_deg', 'maxRange_in', 'maxIncidence_deg', 'frameRateHz', 'latencyMs'], 'sensors.tag'),
  ...rows(robot.sensors.tag.noise, ['bearing_deg', 'rangeFrac', 'open_deg'], 'sensors.tag.noise'),
]));
out.push(section('Tag target (the aim it turns into)', rows(robot.sensors.tag.target, ['holdS', 'maxFireAgeS', 'scanRateDps'], 'sensors.tag.target')));

// ---------------------------------------------------------------- hub / sim
out.push('## Control Hub emulation');
out.push('');
out.push(section('Hub', [
  ...rows(robot.hub, ['loopPeriodMs', 'bulkCacheMode', 'imuLatencyMs', 'encoderVelocityWindowMs', 'commandLatencyMs', 'voltageNoise_V'], 'hub'),
  { path: 'hub.velocityPid', value: `p ${robot.hub.velocityPid.p}, i ${robot.hub.velocityPid.i}, d ${robot.hub.velocityPid.d}, f ${robot.hub.velocityPid.f}`, note: short(robot.hub._velocityPidSource ?? '') },
]));

out.push(section('Battery', rows(params.battery, ['capacity_Ah', 'Rint_ohm'], 'battery')));
out.push(section('Simulation', rows(params.sim, ['dt', 'substepsPerFrame', 'solverIterations', 'ccdOnBalls', 'seed'], 'sim')));
out.push(section('Match', rows(params.match, ['auto_s', 'transition_s', 'teleop_s', 'flowerUnlock_s'], 'match')));

// ---------------------------------------------------------------- provenance guard
//
// TWO BLOCKS MUST NOT SHARE A PROVENANCE NOTE. The chassis block's `_source` was once
// overwritten with the localizer's, word for word, so the chassis mass, inertia and CG lost
// their origin -- and this file is generated from those fields, so the generated
// documentation went on to state that the chassis mass came from an odometry puck. Nothing
// about the value looks wrong; only the duplication gives it away.
//
// ponytail: exact match on notes longer than 80 chars. Short boilerplate ('design parameter')
// is legitimately shared and is skipped; a near-duplicate with one word changed still slips
// through. Reach for a similarity measure only if one ever actually does.
const notes = new Map();
const dupes = [];
(function walk(node, path) {
  if (!node || typeof node !== 'object') return;
  for (const [k, v] of Object.entries(node)) {
    const at = path ? `${path}.${k}` : k;
    if (typeof v === 'string' && /[sS]ource$/.test(k) && v.length > 80) {
      if (notes.has(v)) dupes.push([notes.get(v), at]);
      else notes.set(v, at);
    } else if (v && typeof v === 'object') walk(v, at);
  }
})({ robot, params }, '');
if (dupes.length) {
  for (const [a, b] of dupes) console.error('duplicate _source: ' + a + '  AND  ' + b);
  throw new Error(dupes.length + ' provenance note(s) shared by two blocks -- one of them has lost its origin');
}

writeFileSync(here('../docs/VARIABLES.md'), out.join('\n'));
console.log('docs/VARIABLES.md written');
